menu:
  Home: /
  Archives: /archives
  About: /about

widgets:
- search

cover:
  enable: true
  url: http://ww1.sinaimg.cn/large/6cea169fjw1edgyzma1xcj21kw16ohba.jpg
   
excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

addthis:
  enable: true
  pubid:
  facebook:
  twitter:
  google: true
  pinterest:

fancybox: true

google_analytics: UA-368771XX-X
rss:

comment_provider: duoshuo

# Duoshuo comment
duoshuo:
  short_name: your_id

social:
  github: https://github.com/juneLLL
  weibo: http://weibo.com/u/5295404192/home?wvr=5
  google_plus: 

auto_change:
  enable: true
